root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main"
cmd = "go build -o ./tmp/main ./cmd/server"
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "json"]
exclude_dir = ["tmp", "vendor", "data"]

[log]
time = true